# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# terraform/variables.tf

# ------------------------------------------------------------------------------
# CORE PROJECT CONFIGURATION
# ------------------------------------------------------------------------------

variable "project_id" {
  description = "The Google Cloud Project ID."
  type        = string
}

variable "location" {
  description = "The Google Cloud region/location for deploying resources."
  type        = string
  default     = "us-central1"
}

variable "service_account" {
  description = "The service account email to be used for running pipeline resources and tasks."
  type        = string
  default     = "shoppable-video-sa"
}

# ------------------------------------------------------------------------------
# GOOGLE ACCOUNT & RESOURCE IDS
# ------------------------------------------------------------------------------

variable "merchant_id" {
  description = "The Google Merchant Center Account ID containing product data."
  type        = string
}

variable "google_ads_customer_id" {
  description = <<-EOT
    The Google Ads Customer ID to use for pulling videos from Demand Gen campaigns
    and (optionally) pushing products to product groups. This most likely is
    your Manager (MCC) account.
  EOT
  type        = string
  default     = null
  nullable    = true
}

variable "spreadsheet_id" {
  description = "The Google Sheets Spreadsheet ID containing video URLs and metadata."
  type        = string
  default     = null
  nullable    = true
}

# ------------------------------------------------------------------------------
# GEMINI MODELS & VECTOR SEARCH CONFIGURATION
# ------------------------------------------------------------------------------

variable "generative_model_name" {
  description = "The name of the Gemini generative model used for video analysis."
  type        = string
  default     = "gemini-3-flash-preview"
}

variable "embedding_model_name" {
  description = "The name of the Gemini embedding model used for generating product and video embeddings."
  type        = string
  default     = "gemini-embedding-2-preview"
}

variable "vector_search_embedding_dimensions" {
  description = "The number of dimensions for the multimodal embeddings generated by the embedding model."
  type        = number
  default     = 3072

  validation {
    condition     = contains([768, 1536, 3072], var.vector_search_embedding_dimensions)
    error_message = "The embedding dimensions must be one of: 768, 1536, or 3072."
  }
}

variable "embed_images" {
  description = "Whether to generate embeddings for product images."
  type        = bool
  default     = true
}

variable "num_images_to_embed" {
  description = "The number of product images to use when generating each product's embeddings."
  type        = number
  default     = 3
}

# ------------------------------------------------------------------------------
# PIPELINE LIMITS & EXECUTION CONFIGURATION
# ------------------------------------------------------------------------------

variable "product_limit" {
  description = "The maximum number of products to process and embed from Merchant Center per execution of queue_products."
  type        = number
  default     = 1000
}

variable "video_limit" {
  description = "The maximum number of videos to process and embed from all sources per execution of queue_videos."
  type        = number
  default     = 10
}

variable "number_of_matched_products" {
  description = "The number of matching products to retrieve for each identified product in a video."
  type        = number
  default     = 10
}

# ------------------------------------------------------------------------------
# DATABASE & CONTAINER INFRASTRUCTURE
# ------------------------------------------------------------------------------

variable "bigquery_dataset_id" {
  description = "The ID of the BigQuery dataset used for storing product and video embeddings and product matches."
  type        = string
  default     = "shoppable_video"
}

variable "repository_id" {
  description = "The ID of the Artifact Registry repository for storing container images."
  type        = string
  default     = "shoppable-video"
}

# ------------------------------------------------------------------------------
# WEB APPLICATION & SECURITY (OPTIONAL DEPLOYMENT)
# ------------------------------------------------------------------------------

variable "deploy_webapp" {
  description = "Whether to deploy the web application module."
  type        = bool
  default     = false
}

variable "firestore_database_id" {
  description = "The ID of the Firestore database. Use '(default)' for the default database."
  type        = string
  default     = "(default)"
}

variable "iap_config" {
  description = "Configures IAP for the API backend."
  type = object({
    enable_iap     = bool
    access_members = list(string)
  })
  default = {
    enable_iap     = true
    access_members = ["domain:google.com"]
  }
}

# ------------------------------------------------------------------------------
# AUTOMATION & SCHEDULING CONFIGURATION
# ------------------------------------------------------------------------------

variable "enable_scheduling" {
  description = "If false, scheduled BigQuery queries and Cloud Scheduler jobs are created in a disabled/paused state, allowing manual testing before enabling automation."
  type        = bool
  default     = false
}
