# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""This module defines data models for product-related records."""

import datetime
from typing import List
from app.models import candidate
import pydantic


class MatchedProduct(pydantic.BaseModel):
  """Represents an actual product from Merchant Center.

  Matched Products are generated by taking an identified product from a video
  and finding similar products via Vector Search.

  Attributes:
    matched_product_offer_id: The offer ID of the matched product.
    matched_product_title: The title of the matched product.
    matched_product_brand: The brand of the matched product.
    matched_timestamp: A timestamp that specifies when the matching occurred.
    distance: The distance (in vector search) between the identified product and
      the matched product. Smaller distances indicate higher similarity.
    candidate_status: The candidate status of the matched product.
  """

  matched_product_offer_id: str
  matched_product_title: str
  matched_product_brand: str
  matched_timestamp: datetime.datetime
  distance: float
  candidate_status: candidate.CandidateStatus


class IdentifiedProduct(pydantic.BaseModel):
  """Represents an identified product from a video.

  Attributes:
    uuid: A unique identifier for the identified product in a video.
    title: The title of the identified product.
    description: The description of the identified product.
    relevance_reasoning: a short sentence explaining why this is a product being
      sold and not a prop/object in a video.
    video_timestamp: the time of when the product first appeared in video.
    matched_products: a list of matched products.
  """

  uuid: str
  title: str
  description: str
  relevance_reasoning: str
  video_timestamp: int
  matched_products: List[MatchedProduct]
